//
//  APIPathSelector.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//

import Foundation
import UIKit

protocol APIPathSelectorModalVCDelegate {
    func setSelectedValue(_ value : String)
}

class APIPathSelectorViewController: UITableViewController {

    var cloudLogicAPI: CloudLogicAPI?
    var paths: [String]?
    var pathSuggestions: [String]?
    var initialText: String?
    var delegate:APIPathSelectorModalVCDelegate!
    
    @IBOutlet weak var searchText: UITextField!
    
    func populatePathSuggestions() {
        pathSuggestions = []
        if let searchString = searchText.text {
            if let paths = paths {
                for path: String in paths {
                    if (path.lowercased().contains(searchString.lowercased())) {
                        pathSuggestions?.append(path)
                    }
                }
            }
        }
        tableView.reloadData()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        searchText.text = "/"
        paths = cloudLogicAPI?.paths
        populatePathSuggestions()
        
    }
    
    @IBAction func onEditingChanged(_ sender: AnyObject) {
        populatePathSuggestions()
    }
    
    @IBAction func onSelect(_ sender: AnyObject) {
        delegate.setSelectedValue(searchText.text!)
        self.dismiss(animated: true, completion: nil)
    }
    
    override func numberOfSections(in tableView: UITableView) -> Int {
        guard let pathSuggestions = pathSuggestions else {return 0}
        return pathSuggestions.count
    }
    
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 1
    }
    
    override func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "PathTableCell", for: indexPath) as! PathTableCell
        let path = pathSuggestions![indexPath.section]
        cell.path.text = path
        return cell
    }
    
    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        searchText.text = pathSuggestions![indexPath.section]
    }
}

class PathTableCell: UITableViewCell {
    @IBOutlet weak var path: UILabel!
}
