//
//  CloudLogicAPIFactory.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//

import Foundation
import AWSCore

class CloudLogicAPIFactory {
    static var supportedCloudLogicAPIs: [CloudLogicAPI] {
        
        return [
            CloudLogicAPI(displayName: "meetzam-backend",
                apiDescription: "",
                paths: [
                 "/moviesInTheater", "/moviesInTheater/123",                ],
                endPoint: "https://adi48j5bxk.execute-api.us-east-1.amazonaws.com/Development",
                apiClient: AWSAPI_ADI48J5BXK_MeetzambackendMobileHubClient(forKey: AWSCloudLogicDefaultConfigurationKey)
            ),
        ]
    }
}
