
service: meetzamPushNotification

frameworkVersion: "=1.10.1"

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action: "DynamoDB:*"
      Resource: "arn:aws:dynamodb:us-east-1:397508666882:table/meetzam-mobilehub-1569925313-UserProfile" 
  
    - Effect: Allow
      Action: "lambda:InvokeFunction"
      Resource: "arn:aws:lambda:*:*:*"

    - Effect: Allow
      Action: "sns:*"
      Resource: "arn:aws:sns:us-east-1:397508666882:app/APNS_SANDBOX/meetzam_MOBILEHUB_1569925313"  

functions:

  matchNotification:
    handler: matchNotification.handler
    name: matchNotification-${self:provider.stage}
    description: this function sends push notification to one user's endpoint, this function takes user_id as parameter
    runtime: nodejs6.10
    memorySize: 128
    timeout: 6

  sendMessage:
    handler: sendMessage.handler
    name: sendMessage-${self:provider.stage}
    description: sends mmessage as a push notification to one user's endpoint, this function takes user_id and message string as parameter
    runtime: nodejs6.10
    memorySize: 128
    timeout: 6  
