//
//  Conversation.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//

import Foundation
import UIKit
import AWSDynamoDB

class Conversation: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _conversationId: String?
    var _chatRoomId: String?
    var _createdAt: String?
    var _imageUrlPath: String?
    var _message: String?
    
    class func dynamoDBTableName() -> String {

        return "meetzam-mobilehub-1569925313-Conversation"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_conversationId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_conversationId" : "conversationId",
               "_chatRoomId" : "chatRoomId",
               "_createdAt" : "createdAt",
               "_imageUrlPath" : "imageUrlPath",
               "_message" : "message",
        ]
    }
}
