//
//  UserProfile.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.10
//

import Foundation
import UIKit
import AWSDynamoDB

class UserProfile: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _phone: String?
    var _name: String?
    var _pushTargetArn: String?
    
    class func dynamoDBTableName() -> String {

        return "meetzam-mobilehub-1569925313-UserProfile"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_phone"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_phone" : "phone",
               "_name" : "name",
               "_pushTargetArn" : "pushTargetArn",
        ]
    }
}
